import SectionDaftarFitur from "@/section/homepage/SectionDaftarFitur";
import SectionHeaderHero from "@/section/homepage/SectionHeaderHero";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "EcoCrestConnect | Home",
  description: "Generated by create next app",
};

const Home = () => {
  return (
    <>
      <SectionHeaderHero />
      <SectionDaftarFitur />
    </>
  );
};

export default Home;
