import SectionHeaderHero from "@/section/aboutus/SectionHeaderHero";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "EcoCrestConnect | About Us",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <>
      <SectionHeaderHero />
    </>
  );
};

export default page;
