import SectionDaftarLogoMitra from "@/section/aboutus/SectionDaftarLogoMitra";
import SectionDaftarPenghargaan from "@/section/aboutus/SectionDaftarPenghargaan";
import SectionHeaderHero from "@/section/aboutus/SectionHeaderHero";
import SectionTentang from "@/section/aboutus/SectionTentang";
import SectionTim from "@/section/aboutus/SectionTim";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "EcoCrestConnect | About Us",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <>
      <SectionHeaderHero />
      <SectionTentang />
      <SectionDaftarLogoMitra />
      <SectionTim />
      <SectionDaftarPenghargaan />
    </>
  );
};

export default page;
